[project]
name = "audio-visual"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pillow>=11.3.0",
    "pytest>=8.4.1",
]

[tool.uv]